MODEL:
  #TYPE: resnet
  #DEPTH: 20
  NUM_CLASSES: 10
  ARCH: taowei.torch2.models.darts.model.NetworkCIFAR
  AUXILIARY_WEIGHT: 0.4
  DROP_PATH_PROB: 0.2
#RESNET:
  #TRANS_FUN: basic_transform
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.025
  LR_POLICY: cos
  MAX_EPOCH: 600
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0003
  GRAD_CLIP: 5.0
TRAIN:
  DATASET: cifar10
  SPLIT: train
  BATCH_SIZE: 96
  IM_SIZE: 32
  EVAL_PERIOD: 1
TEST:
  DATASET: cifar10
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
  BACKEND: pil
  DATA_AUG: cifar_cutout
  DATA_ROOT: /gdata/cifar10
CUDNN:
  BENCHMARK: False
OUT_DIR: .
