MODEL:
  #TYPE: resnet
  #DEPTH: 50
  NUM_CLASSES: 1000
  ARCH: taowei.torch2.models.darts.model.NetworkImageNet
  AUXILIARY_WEIGHT: 0.4 # NEW!
  DROP_PATH_PROB: 0.0 # NOT SET!
  LABEL_SMOOTH: 0.1
#RESNET:
  #TRANS_FUN: bottleneck_transform
  #NUM_GROUPS: 1
  #WIDTH_PER_GROUP: 64
  #STRIDE_1X1: False
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.5 # 0.1
  LR_POLICY: linear # steps
  #STEPS: [1] # [0, 30, 60, 90]
  #LR_MULT: 0.97 # 0.1
  LR_MIN: 1e-5 # NOT USED: 0.5/250 = 2e-3
  COOLDOWN_EPOCHS: 5 # LINEAR SCHEDULER NEEDS COOLDOWN 
  MAX_EPOCH: 250 # 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 3e-5 # 0.0001, CAN IMPACT PERFORMANCE SIGNIFICANTLY
  GRAD_CLIP: 5.0 # NEW!
  WARMUP_EPOCHS: 5 # NEW to PDARTS
  WARMUP_FACTOR: 0.1
  WARMUP_GRADUAL: True
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 1024 # 128 # 256
  IM_SIZE: 224
  EVAL_PERIOD: 1
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 1000 # 100 # 200
  IM_SIZE: 256
NUM_GPUS: 8
DATA_LOADER:
  #NUM_WORKERS: 4 # Default DDS: 8 workers/GPU
  BACKEND: pil # NEW: backend
  DATA_AUG: fbresearch_cj
  DATA_ROOT: /gdata/ImageNet2012
CUDNN:
  BENCHMARK: True
OUT_DIR: .
